### ISSUE TITLE
Caddyfile can be even simpler

### ISSUE THREAD

**Issue by mholt** [RecuencoJones/caddy-vue-router#1]
The current Caddyfile:

```
:8080 {
  handle {
    root * {$WWW_ROOT}
    try_files {path} /index.html
    file_server
  }
}
```

can be:

```
:8080

root * {$WWW_ROOT}
try_files {path} /index.html
file_server
```

They are equivalent! :)

**Comment by RecuencoJones** [comment]
Thanks a lot @mholt! 

I find myself using this syntax more often than not as I can reuse it when application starts growing (i.e: adding reverse proxies) as it means less changes 😄

If I'm not mistaken, even the `handle {}` directive is redundant as there are no other handlers, is that right?

Also, when I was building it I found a problem with `root` directive and had to add `*` matcher to it even though it's implicitly matched by `handle { ... }`, is that expected?

**Comment by mholt** [comment]
> I find myself using this syntax more often than not as I can reuse it when application starts growing (i.e: adding reverse proxies) as it means less changes 😄

That's fine, but when giving examples I find that keeping them minimal is best so people don't get the wrong idea.

> If I'm not mistaken, even the handle {} directive is redundant as there are no other handlers, is that right?

Yep, because there is nothing outside the `handle` block; i.e. no other handler blocks.

> Also, when I was building it I found a problem with root directive and had to add * matcher to it even though it's implicitly matched by handle { ... }, is that expected?

Yeah, if the first (non-matcher) argument looks like a path matcher you need to add a matcher token to disambiguate: https://caddyserver.com/docs/caddyfile/matchers#wildcard-matchers - also explained in a few places on this page: https://caddyserver.com/docs/caddyfile/directives/root#syntax

**Comment by RecuencoJones** [comment]
> Yeah, if the first (non-matcher) argument looks like a path matcher you need to add a matcher token to disambiguate: https://caddyserver.com/docs/caddyfile/matchers#wildcard-matchers - also explained in a few places on this page: https://caddyserver.com/docs/caddyfile/directives/root#syntax

That rings a bell! Thanks a lot for the pointers!
